package transform

import (
	"testing"
	"time"

	"github.com/florinutz/pgcdc/testutil"
)

func TestDedup_DropsExactDuplicate(t *testing.T) {
	fn := Dedup("", 1*time.Hour, 100)

	ev := testutil.MakeEvent("ch", `{"id":"1"}`)
	// First call: not a duplicate.
	_, err := fn(ev)
	if err != nil {
		t.Fatalf("first call should pass, got: %v", err)
	}

	// Second call with same event ID: duplicate.
	_, err = fn(ev)
	if err != ErrDropEvent {
		t.Fatalf("second call should return ErrDropEvent, got: %v", err)
	}
}

func TestDedup_PassesAfterTTLExpiry(t *testing.T) {
	fn := Dedup("", 1*time.Millisecond, 100)

	ev := testutil.MakeEvent("ch", `{"id":"1"}`)
	_, err := fn(ev)
	if err != nil {
		t.Fatalf("first call should pass, got: %v", err)
	}

	// Wait for TTL to expire.
	time.Sleep(5 * time.Millisecond)

	_, err = fn(ev)
	if err != nil {
		t.Fatalf("call after TTL expiry should pass, got: %v", err)
	}
}

func TestDedup_LRUEvictionAtMaxKeys(t *testing.T) {
	fn := Dedup("", 1*time.Hour, 2)

	ev1 := testutil.MakeEvent("ch", `{"id":"1"}`)
	ev2 := testutil.MakeEvent("ch", `{"id":"2"}`)
	ev3 := testutil.MakeEvent("ch", `{"id":"3"}`)

	// Fill cache with ev1 and ev2.
	if _, err := fn(ev1); err != nil {
		t.Fatalf("ev1 first: %v", err)
	}
	if _, err := fn(ev2); err != nil {
		t.Fatalf("ev2 first: %v", err)
	}

	// Insert ev3 — should evict ev1 (LRU).
	if _, err := fn(ev3); err != nil {
		t.Fatalf("ev3 first: %v", err)
	}

	// ev1 should no longer be in cache (evicted).
	if _, err := fn(ev1); err != nil {
		t.Fatalf("ev1 after eviction should pass, got: %v", err)
	}

	// ev2 should still be duplicate (not evicted because ev3 evicted ev1).
	// Actually ev2 was the second inserted and ev1 was the tail, so ev1 was evicted.
	// After inserting ev3: cache has [ev3, ev2]. Then inserting ev1 again evicts ev2.
	// So ev2 should now be gone too.
	if _, err := fn(ev2); err != nil {
		t.Fatalf("ev2 after ev1 re-insert should pass, got: %v", err)
	}
}

func TestDedup_NestedFieldPathExtraction(t *testing.T) {
	fn := Dedup("row.id", 1*time.Hour, 100)

	ev1 := testutil.MakeEvent("ch", `{"row":{"id":"abc"}}`)
	ev2 := testutil.MakeEvent("ch", `{"row":{"id":"abc"}}`)
	ev3 := testutil.MakeEvent("ch", `{"row":{"id":"def"}}`)

	if _, err := fn(ev1); err != nil {
		t.Fatalf("ev1 should pass: %v", err)
	}

	// Same key path value — duplicate.
	if _, err := fn(ev2); err != ErrDropEvent {
		t.Fatalf("ev2 with same row.id should be dropped, got: %v", err)
	}

	// Different key path value — not duplicate.
	if _, err := fn(ev3); err != nil {
		t.Fatalf("ev3 with different row.id should pass: %v", err)
	}
}

func TestDedup_EmptyKeyPathUsesEventID(t *testing.T) {
	fn := Dedup("", 1*time.Hour, 100)

	ev1 := testutil.MakeEvent("ch", `{"id":"1"}`)
	ev2 := testutil.MakeEvent("ch", `{"id":"1"}`)

	if _, err := fn(ev1); err != nil {
		t.Fatalf("ev1 should pass: %v", err)
	}

	// ev2 has a different event ID (generated by MakeEvent), so it should pass
	// even though the payload is the same.
	if _, err := fn(ev2); err != nil {
		t.Fatalf("ev2 with different event ID should pass: %v", err)
	}
}
